// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "react-hot-toast";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   // return (
//   //   <html lang="en">
//   //     <body
//   //       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//   //     >
//   //       {children}
//   //     </body>
//   //   </html>
//   // );
//   return (
//     <html lang="en">
//       <body>
//         {children}
//         <Toaster position="bottom-right" />
//       </body>
//     </html>
//   )
// }


"use client"
import { useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'
import { Toaster } from 'react-hot-toast'
import './globals.css'



export default function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = createClient()
  const router = useRouter()

  useEffect(() => {
    document.title = "Mission Control | Sniper.ai";
  }, []);

  useEffect(() => {
    // Listen for Auth changes (Login, Logout, Token Refresh)
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (event === 'SIGNED_IN') {
        router.refresh()
      }
      if (event === 'SIGNED_OUT') {
        router.push('/login')
        router.refresh()
      }
    })

    return () => subscription.unsubscribe()
  }, [router, supabase])

  return (
    <html lang="en">
      <body className="antialiased">
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  )
}